
name: Assign Copilot to Issues

"on":
  issues:
    types: [opened]

jobs:
  assign-copilot:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Assign Copilot
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Step 1: Verify that Copilot coding agent is enabled
            const suggestedActorsQuery = `
              query {
                repository(owner: "${owner}", name: "${repo}") {
                  suggestedActors(capabilities: [CAN_BE_ASSIGNED], first: 100) {
                    nodes {
                      login
                      __typename
                      ... on Bot {
                        id
                      }
                      ... on User {
                        id
                      }
                    }
                  }
                }
              }
            `;

            const suggestedActorsResult = await github.graphql(suggestedActorsQuery);
            const copilotBot = suggestedActorsResult.repository.suggestedActors.nodes.find(
              node => node.login === 'copilot-swe-agent'
            );

            if (!copilotBot) {
              throw new Error('Copilot coding agent is not enabled for this repository');
            }

            // Step 2: Fetch the GraphQL global ID of the issue
            const issueQuery = `
              query {
                repository(owner: "${owner}", name: "${repo}") {
                  issue(number: ${issueNumber}) {
                    id
                    title
                  }
                }
              }
            `;

            const issueResult = await github.graphql(issueQuery);
            const issueId = issueResult.repository.issue.id;

            // Step 3: Assign the existing issue to Copilot
            const assignMutation = `
              mutation {
                replaceActorsForAssignable(input: {assignableId: "${issueId}", actorIds: ["${copilotBot.id}"]}) {
                  assignable {
                    ... on Issue {
                      id
                      title
                      assignees(first: 10) {
                        nodes {
                          login
                        }
                      }
                    }
                  }
                }
              }
            `;

            await github.graphql(assignMutation);
