

name: Assign Copilot to Issues

on:
  issues:
    types: [opened, edited, labeled]


jobs:
  assign-copilot:
    runs-on: ubuntu-latest
    if: |
      github.event.issue.title.startsWith('copilot:') ||
      contains(github.event.issue.labels.*.name, 'copilot-task')
    steps:
      - name: Assign Copilot
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issueNumber = context.issue.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            await github.rest.issues.addAssignees({
              owner,
              repo,
              issue_number: issueNumber,
              assignees: ['copilot']
            });
